apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1729099754050
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
        - name: test3
          image: skdemoacr.azurecr.io/samples/contoso-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
