apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  labels:
    app: workflow
    kubernetes.azure.com/generator: devhub
  namespace: sample-app-namespace-1730322998850
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: registry1730323095263.azurecr.io/image-workflow-1730322998845:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
