apiVersion: v1
kind: Service
metadata:
  name: workflow
  namespace: sample-app-namespace-1730322998850
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000