apiVersion: v1
kind: Service
metadata:
  name: ca-workflow1
  namespace: namespace-workflow-1749660750119
  labels:
    app.kubernetes.io/name: ca-workflow1
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ca-workflow1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000